### ISSUE TITLE
TypeError: Unable to get property 'insert' of undefined or null reference

### ISSUE THREAD

**Issue by supasheva** [ashteya/ionic-tutorial-lokijs#2]
```

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
HTML1300: Navigation occurred.
localhost:8100
[LokiCordovaFSAdapter] loading database
TypeError: Unable to get property 'insert' of undefined or null reference
   at addBirthday (http://localhost:8100/js/birthday.service.js:51:13)
   at $scope.saveBirthday (http://localhost:8100/js/overview.controller.js:43:5)
   at fn (Function code:2:204)
   at Anonymous function (http://localhost:8100/lib/ionic/js/ionic.bundle.js:57514:9)
   at Scope.prototype.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:24673:9)
   at Scope.prototype.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:24772:11)
   at Anonymous function (http://localhost:8100/lib/ionic/js/ionic.bundle.js:57513:7)
   at eventHandler (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12098:9)

```

**Comment by romuloctba** [comment]
same here

**Comment by kiminiuso** [comment]
same here
